name: Release
on: 
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latests
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        with: 
          node-versions: "16.x"
      - name: Install Dependencies
        run: |
          npm install
          npm run build --if-present
          npm run package:windows
